// Local team logos stored in /public/logos/
// No external API calls needed - all served from the project itself

export const TEAM_LOGOS: Record<string, string> = {
    // East Region
    "Duke": "/logos/duke.png",
    "Siena": "/logos/siena.png",
    "Ohio State": "/logos/ohio_state.png",
    "TCU": "/logos/tcu.png",
    "St. John's": "/logos/st_johns.png",
    "Northern Iowa": "/logos/northern_iowa.png",
    "Kansas": "/logos/kansas.png",
    "Cal Baptist": "/logos/cal_baptist.png",
    "Louisville": "/logos/louisville.png",
    "South Florida": "/logos/south_florida.png",
    "Michigan State": "/logos/michigan_state.png",
    "North Dakota State": "/logos/north_dakota_state.png",
    "UCLA": "/logos/ucla.png",
    "UCF": "/logos/ucf.png",
    "UConn": "/logos/uconn.png",
    "Furman": "/logos/furman.png",

    // Midwest Region
    "Michigan": "/logos/michigan.png",
    "UMBC": "/logos/umbc.png",
    "Howard": "/logos/howard.png",
    "Georgia": "/logos/georgia.png",
    "Saint Louis": "/logos/saint_louis.png",
    "Texas Tech": "/logos/texas_tech.png",
    "Akron": "/logos/akron.png",
    "Alabama": "/logos/alabama.png",
    "Hofstra": "/logos/hofstra.png",
    "Tennessee": "/logos/tennessee.png",
    "Miami (OH)": "/logos/miami_oh.png",
    "SMU": "/logos/smu.png",
    "Virginia": "/logos/virginia.png",
    "Wright State": "/logos/wright_state.png",
    "Kentucky": "/logos/kentucky.png",
    "Santa Clara": "/logos/santa_clara.png",
    "Iowa State": "/logos/iowa_state.png",
    "Tennessee State": "/logos/tennessee_state.png",

    // South Region
    "Florida": "/logos/florida.png",
    "Prairie View A&M": "/logos/prairie_view.png",
    "Lehigh": "/logos/lehigh.png",
    "Clemson": "/logos/clemson.png",
    "Iowa": "/logos/iowa.png",
    "Vanderbilt": "/logos/vanderbilt.png",
    "McNeese": "/logos/mcneese.png",
    "Nebraska": "/logos/nebraska.png",
    "Troy": "/logos/troy.png",
    "North Carolina": "/logos/north_carolina.png",
    "VCU": "/logos/vcu.png",
    "Illinois": "/logos/illinois.png",
    "Penn": "/logos/penn.png",
    "Saint Mary's": "/logos/saint_marys.png",
    "Texas A&M": "/logos/texas_am.png",
    "Houston": "/logos/houston.png",
    "Idaho": "/logos/idaho.png",

    // West Region
    "Arizona": "/logos/arizona.png",
    "LIU": "/logos/liu.png",
    "Villanova": "/logos/villanova.png",
    "Utah State": "/logos/utah_state.png",
    "Wisconsin": "/logos/wisconsin.png",
    "High Point": "/logos/high_point.png",
    "Arkansas": "/logos/arkansas.png",
    "Hawai'i": "/logos/hawaii.png",
    "BYU": "/logos/byu.png",
    "Texas": "/logos/texas.png",
    "NC State": "/logos/nc_state.png",
    "Gonzaga": "/logos/gonzaga.png",
    "Kennesaw State": "/logos/kennesaw_state.png",
    "Miami (FL)": "/logos/miami_fl.png",
    "Missouri": "/logos/missouri.png",
    "Purdue": "/logos/purdue.png",
    "Queens": "/logos/queens.png",
};
